jobs:
 - name: u14nruball
   type: runSh
   runtime:
     container: true
   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/u14ruball"
             imageTag: master
         script:
          - rvm list
